# Puerto del servicio
server.port=8085

# Nombre de la aplicacion
spring.application.name=servicio-reportes

# Endpoints de los otros servicios
servicio.auditoria.url=http://localhost:8081
servicio.identidad.url=http://localhost:8082
servicio.autorizacion.url=http://localhost:8083
