server.port=8082

spring.application.name=servicio_identidad

spring.datasource.url=jdbc:postgresql://localhost:5432/servicio_identidad_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver



app.jwt.secret=ClaveUltraSeguraParaJWT256BitsGobierno2026
app.jwt.expiracion=3600000


spring.jpa.hibernate.ddl-auto=validate

servicio.auditoria.url=http://localhost:8081