server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: servicio-auditoria
              uri: http://localhost:8081
              predicates:
                - Path=/api/auditoria/**
              filters:
                - StripPrefix=1
        
            - id: servicio-identidad
              uri: http://localhost:8082
              predicates:
                - Path=/api/usuarios/**
              filters:
                - StripPrefix=1
        
            - id: servicio-autorizacion-roles
              uri: http://localhost:8083
              predicates:
                - Path=/api/roles/**
              filters:
                - StripPrefix=1

            - id: servicio-autorizacion-permisos
              uri: http://localhost:8083
              predicates:
                - Path=/api/permisos/**
              filters:
                - StripPrefix=1
        
            - id: servicio-reportes
              uri: http://localhost:8085
              predicates:
                - Path=/api/reportes/**
              filters:
                - StripPrefix=1
          
          httpclient:
            connect-timeout: 5000
            response-timeout: 30000
      
      forward-headers-strategy: native
